version: "3"
services:
  # anton_api:
  #   container_name: anton_api
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #   command: cargo watch -x run
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - anton_postgres_write
  #     - anton_postgres_read

  anton_postgres_event_store:
    container_name: anton_postgres_event_store
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: anton_event_store

  anton_postgres_read:
    container_name: anton_postgres_read
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: anton_read